
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SECCESS = "GET_PRODUCT_SECCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";


export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SECCESS = "GET_BRAND_SECCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";



